// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFX4d7le5Afrk4HryvR-JxA1JLW1FHvXI',
    appId: '1:802368686218:web:d64d2db14d8aed9c1dc573',
    messagingSenderId: '802368686218',
    projectId: 'fitlens-816b5',
    authDomain: 'fitlens-816b5.firebaseapp.com',
    storageBucket: 'fitlens-816b5.firebasestorage.app',
    measurementId: 'G-BC0VQWBR63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl15ewh1mCfGBCHlh4SLyGlIyJHStImWI',
    appId: '1:802368686218:android:1ec1b81cdb0d3d9a1dc573',
    messagingSenderId: '802368686218',
    projectId: 'fitlens-816b5',
    storageBucket: 'fitlens-816b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQj1ol5CJ_k_beG2CJT_xHIdFj0MbKIgw',
    appId: '1:802368686218:ios:d633cbe4e19948101dc573',
    messagingSenderId: '802368686218',
    projectId: 'fitlens-816b5',
    storageBucket: 'fitlens-816b5.firebasestorage.app',
    iosBundleId: 'com.example.fitlens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQj1ol5CJ_k_beG2CJT_xHIdFj0MbKIgw',
    appId: '1:802368686218:ios:d633cbe4e19948101dc573',
    messagingSenderId: '802368686218',
    projectId: 'fitlens-816b5',
    storageBucket: 'fitlens-816b5.firebasestorage.app',
    iosBundleId: 'com.example.fitlens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFX4d7le5Afrk4HryvR-JxA1JLW1FHvXI',
    appId: '1:802368686218:web:d0732d3e7aa8f3a51dc573',
    messagingSenderId: '802368686218',
    projectId: 'fitlens-816b5',
    authDomain: 'fitlens-816b5.firebaseapp.com',
    storageBucket: 'fitlens-816b5.firebasestorage.app',
    measurementId: 'G-DXW445CF9Q',
  );
}
