import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'core/constants/api_constants.dart';
import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
import 'core/providers/theme_provider.dart';

// Entry point of the FitLens app
void main() async {
  // Ensures Flutter's engine and widget bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Edge-to-edge transparent system overlay for Android 13/14/15 and iOS
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: Colors.transparent,
      systemNavigationBarDividerColor: Colors.transparent,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);

  // Initializes custom API server URL from storage
  await ApiConstants.init();

  // Initializes Firebase using the platform-specific configuration
  // generated by the FlutterFire CLI (firebase_options.dart)
  try {
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    }
  } catch (e) {
    // If initialization fails with duplicate app, it's already natively initialized.
    // We can safely ignore it.
  }

  // Runs the app only after Firebase has been successfully initialized
  runApp(
    const ProviderScope(
      child: FitLensApp(),
    ),
  );
}

// Root widget of the FitLens app
class FitLensApp extends ConsumerWidget {
  const FitLensApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);
    final currentThemeMode = ref.watch(themeProvider);

    return MaterialApp.router(
      // Removes the debug banner in the top-right corner
      debugShowCheckedModeBanner: false,
      title: 'FitLens',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: currentThemeMode,
      routerConfig: router,
    );
  }
}