import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'core/widgets/splash_screen.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'features/authentication/presentation/screens/login_screen.dart';
// Entry point of the FitLens app
void main() async {
  // Ensures Flutter's engine and widget bindings are initialized
  // before we run any async code (required before calling Firebase.initializeApp)
  WidgetsFlutterBinding.ensureInitialized();

  // Initializes Firebase using the platform-specific configuration
  // generated by the FlutterFire CLI (firebase_options.dart)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Runs the app only after Firebase has been successfully initialized
  runApp(
    const ProviderScope(
      child: FitLensApp(),
    ),
  );
}

// Root widget of the FitLens app
class FitLensApp extends StatelessWidget {
  const FitLensApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Removes the debug banner in the top-right corner
      debugShowCheckedModeBanner: false,
      title: 'FitLens',
      // Simple placeholder home screen to confirm the app runs
      // after Firebase initialization (no auth or business logic here)
      home: const LoginScreen(),
    );
  }
}