import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../domain/entities/social_post_entity.dart';
import '../../domain/repositories/social_repository.dart';
import '../../data/datasources/social_remote_data_source.dart';
import '../../data/repositories/social_repository_impl.dart';
import '../../../authentication/presentation/providers/auth_provider.dart';

final firebaseFirestoreProvider = Provider<FirebaseFirestore>((ref) {
  return FirebaseFirestore.instance;
});

final socialRemoteDataSourceProvider = Provider<SocialRemoteDataSource>((ref) {
  return SocialRemoteDataSourceImpl(
    firestore: ref.watch(firebaseFirestoreProvider),
  );
});

final socialRepositoryProvider = Provider<SocialRepository>((ref) {
  return SocialRepositoryImpl(
    remoteDataSource: ref.watch(socialRemoteDataSourceProvider),
  );
});

final socialFeedProvider = StreamProvider<List<SocialPostEntity>>((ref) {
  final repository = ref.watch(socialRepositoryProvider);
  return repository.getGlobalFeed();
});

class CreateSocialPostNotifier extends Notifier<bool> {
  @override
  bool build() => false;

  Future<void> createPost(String imageUrl, String description) async {
    final user = ref.read(authStateChangesProvider).value;
    final uid = user?.uid ?? 'dummy_user_id';
    final username = user?.email?.split('@').first ?? 'GuestUser';

    state = true;
    try {
      final repository = ref.read(socialRepositoryProvider);
      
      final newPost = SocialPostEntity(
        id: '', // Will be generated by firestore
        userId: uid,
        username: username,
        imageUrl: imageUrl,
        description: description,
        likesCount: 0,
        timestamp: DateTime.now(),
      );

      await repository.createPost(newPost);
    } finally {
      state = false;
    }
  }

  Future<void> likePost(String postId) async {
    final user = ref.read(authStateChangesProvider).value;
    if (user == null) return;
    final repository = ref.read(socialRepositoryProvider);
    await repository.likePost(postId, user.uid);
  }
}

final createSocialPostProvider = NotifierProvider<CreateSocialPostNotifier, bool>(() {
  return CreateSocialPostNotifier();
});
