import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import '../../../authentication/presentation/providers/auth_provider.dart';
import '../../domain/entities/closet_item_entity.dart';
import '../../domain/repositories/closet_repository.dart';
import '../../domain/usecases/analyze_closet_item_usecase.dart';
import '../../data/datasources/closet_remote_data_source.dart';
import '../../data/repositories/closet_repository_impl.dart';

final firebaseFirestoreProvider = Provider<FirebaseFirestore>((ref) {
  return FirebaseFirestore.instance;
});

final closetRemoteDataSourceProvider = Provider<ClosetRemoteDataSource>((ref) {
  return ClosetRemoteDataSourceImpl(
    firestore: ref.watch(firebaseFirestoreProvider),
  );
});

final closetRepositoryProvider = Provider<ClosetRepository>((ref) {
  return ClosetRepositoryImpl(
    remoteDataSource: ref.watch(closetRemoteDataSourceProvider),
  );
});

final analyzeClosetItemUseCaseProvider = Provider<AnalyzeClosetItemUseCase>((ref) {
  return AnalyzeClosetItemUseCase();
});

class SelectedGenderNotifier extends Notifier<String> {
  @override String build() => 'All';
  void update(String val) => state = val;
}
final selectedGenderProvider = NotifierProvider<SelectedGenderNotifier, String>(SelectedGenderNotifier.new);

class SelectedSeasonNotifier extends Notifier<String> {
  @override String build() => 'All';
  void update(String val) => state = val;
}
final selectedSeasonProvider = NotifierProvider<SelectedSeasonNotifier, String>(SelectedSeasonNotifier.new);

class SelectedCategoryNotifier extends Notifier<String> {
  @override String build() => 'All';
  void update(String val) => state = val;
}
final selectedCategoryProvider = NotifierProvider<SelectedCategoryNotifier, String>(SelectedCategoryNotifier.new);

final filteredClosetProvider = Provider<AsyncValue<List<ClosetItemEntity>>>((ref) {
  final closetItems = ref.watch(closetProvider);
  final gender = ref.watch(selectedGenderProvider);
  final season = ref.watch(selectedSeasonProvider);
  final category = ref.watch(selectedCategoryProvider);

  return closetItems.when(
    data: (items) {
      final filtered = items.where((item) {
        final matchGender = gender == 'All' || item.category.toLowerCase().contains(gender.toLowerCase());
        final matchSeason = season == 'All' || item.season.toLowerCase().contains(season.toLowerCase());
        final matchCategory = category == 'All' || item.category.toLowerCase().contains(category.toLowerCase());
        return matchGender && matchSeason && matchCategory;
      }).toList();
      return AsyncValue.data(filtered);
    },
    loading: () => const AsyncValue.loading(),
    error: (e, st) => AsyncValue.error(e, st),
  );
});


class ClosetNotifier extends AsyncNotifier<List<ClosetItemEntity>> {
  late ClosetRepository _repository;
  late AnalyzeClosetItemUseCase _analyzeUseCase;

  @override
  Future<List<ClosetItemEntity>> build() async {
    _repository = ref.watch(closetRepositoryProvider);
    _analyzeUseCase = ref.watch(analyzeClosetItemUseCaseProvider);
    
    final user = ref.watch(authStateChangesProvider).value;
    if (user == null) {
      return [];
    }
    
    return await _repository.getClosetItems(user.uid);
  }

  Future<void> addClosetItem(Uint8List imageBytes, {String? overrideCategory, String? overrideSeason}) async {
    final user = ref.read(authStateChangesProvider).value;
    if (user == null) throw Exception('User not logged in');
    
    try {
      // 1. Analyze image (with 15 second timeout)
      final analysis = await _analyzeUseCase(imageBytes).timeout(
        const Duration(seconds: 15),
        onTimeout: () {
          debugPrint('Gemini API timeout, using fallback');
          return {
            "category": "T-Shirt",
            "color": "Unknown",
            "season": "All Season"
          };
        },
      );
      
      // 2. Upload image (with 15 second timeout)
      final fileName = '${DateTime.now().millisecondsSinceEpoch}.jpg';
      final imageUrl = await _repository.uploadImage(imageBytes, fileName).timeout(
        const Duration(seconds: 15),
        onTimeout: () {
          throw Exception('Image upload to Cloudflare timed out after 15 seconds.');
        },
      );
      
      // 3. Create Entity
      final newItem = ClosetItemEntity(
        id: '', // Will be generated by firestore
        userId: user.uid,
        imageUrl: imageUrl,
        category: overrideCategory ?? analysis['category'] ?? 'Other',
        color: analysis['color'] ?? 'Unknown',
        season: overrideSeason ?? analysis['season'] ?? 'All Season',
        dateAdded: DateTime.now(),
      );
      
      // 4. Save to Firestore
      await _repository.addClosetItem(newItem);
      
      // 5. Update state by re-fetching
      state = const AsyncValue.loading();
      state = AsyncValue.data(await _repository.getClosetItems(user.uid));
    } catch (e, st) {
      // If we error, restore previous state or surface the error
      state = AsyncValue.error(e, st);
      rethrow;
    }
  }

  Future<void> deleteClosetItem(String itemId) async {
    final user = ref.read(authStateChangesProvider).value;
    if (user == null) throw Exception('User not logged in');

    try {
      await _repository.deleteClosetItem(itemId);
      state.whenData((items) {
        state = AsyncValue.data(items.where((i) => i.id != itemId).toList());
      });
    } catch (e, st) {
      state = AsyncValue.error(e, st);
      rethrow;
    }
  }
}

final closetProvider = AsyncNotifierProvider<ClosetNotifier, List<ClosetItemEntity>>(() {
  return ClosetNotifier();
});

class IsUploadingNotifier extends Notifier<bool> {
  @override
  bool build() => false;

  void set(bool value) {
    state = value;
  }
}

final isUploadingProvider = NotifierProvider<IsUploadingNotifier, bool>(() {
  return IsUploadingNotifier();
});
